name: Output
on: workflow_dispatch
jobs:
  Output:
    runs-on: ubuntu-latest
    steps:
      - name: Output context
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 18
        run: echo ${{ github }}