name: Output
on: workflow_dispatch
jobs:
  Output:
    runs-on: ubuntu-latest
    steps:
      - name: Output context
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with: 
          node-version: 18
      - name: Print metadata
        run: echo ${{ github }}