name: Worklow
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Test code
        run: npm run lint
  test: 
    runs-on: ubuntu-latest
    needs: lint
    steps:  
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Code test
        run : npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: deploy
        run: npm build
          